x-service-templates:
  api: &api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    networks:
      - payment-backend
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"
  payment-worker: &payment-worker
    build:
      context: .
      dockerfile: ./payment-worker/Dockerfile
    networks:
      - payment-backend
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - payment-backend
  nginx:
    image: nginx:latest
    ports: 
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - payment-backend
    depends_on:
      - api-1
      - api-2

  api-1:
    <<: *api
    container_name: api-1
    hostname: api-1
    ports:
      - 3001:3001
  api-2:
    <<: *api
    container_name: api-2
    hostname: api-2
    ports:
      - 3002:3001

  payment-worker:
    <<: *payment-worker
    container_name: payment-worker
    hostname: payment-worker

networks:
  payment-backend:
    name: payment-backend
    driver: bridge
